Fix Command Error(en)
Command does not include destination for download file, making this following command exception:
CommandException: Wrong number of arguments for "cp" command.
'./' has to be included after previous command.